### ISSUE TITLE
RexMarkitup und MForm

### ISSUE THREAD

**Issue by isospin** [joachimdoerr/mform#50]
Hallo Joachim,

ich verwende gerade RexMarkitup in MForm. Dort gibt es zwei Probleme. Das erste ist eher kosmetisch: die Buttonbar von RexMarkitup hat einen komischen Abstand nach unten (erstes Bild).
Das eigentliche Problem ist der Fullscreenmodus, der bei Verwendung mit MForm so verschoben ist, das er nicht mehr nutzbar ist (zweites Bild).

Hast du eine Idee, oder ist das eher ein Problem von RexMarkitup?

Ansonsten ein super Addon, genau wie Basecondition. Vielen Dank dafür!

Viele Grüße
Ingo

![image](https://cloud.githubusercontent.com/assets/1148347/2927850/018abaec-d774-11e3-822a-640873e34c1b.png)
![image](https://cloud.githubusercontent.com/assets/1148347/2927871/21574142-d774-11e3-91a9-35823099ad2c.png)

**Comment by joachimdoerr** [comment]
https://github.com/joachimdoerr/mform/commit/15d907829ad79426396204314bfd007ad15fe659

Wurde mit dem commit gefixt. Bitte nach Möglichkeit testen.
