### ISSUE TITLE
Ausgabe von " array() "

### ISSUE THREAD

**Issue by olien** [joachimdoerr/mform#52]
Hallo,

wenn ich folgenden Code nutze (funktioniert)

	$options = array("hallo","test");

	$objForm = new mform();

		$objForm->addMultiSelectField(1);
		$objForm->addOptions($options);
		$objForm->setSize(5);
		$objForm->setLabel('Slider wählen');

	echo $objForm->show_mform();  

wird bei der Eingabe über der mform Ausgabe

array() 

ausgegeben.

Grüße
Oliver
(Und danke für die Tipps!)

**Comment by joachimdoerr** [comment]
Also um das zu klären: 

* MForm wandelt deine Options in ein Array mit Schlüssel um der Schlüssel ist immer nummerisch
* Der numerische Schlüssel wird kammergetrennt in ein hidden Input-Textfeld gepappt und dann in als Value in die DB gekippt.

Du hättest also in deinem Fall für "hallo" => 0 und für "test" => 1. Wählst du bei, dann wird in das Textinput "0,1" geschrieben. Du kannst dann diese Werte via explode aus dem String selektieren lassen. Ich hoffe das klärt die frage. 

Und sorry für die späte Antwort...
