### ISSUE TITLE
REX_LINKLIST_BUTTON fehlerhaft

### ISSUE THREAD

**Issue by Hirbod** [joachimdoerr/mform#53]
Hi Joachim,

REX_LINKLIST_BUTTON wird zwar ausgegeben und gespeichert, aber sobald ich das Modul erneut öffne, ist der Inhalt leer. Also die ausgewählten Artikel sind weg, obwohl diese in der DB sind. Glaube da ist ein Fehler in der Ausgabe oder ähnliches.

LG
Hirbod

**Comment by joachimdoerr** [comment]
Ich schließe hier sollte das Problem nochmal auftreten bitte reopen.

**Comment by crayssnlabs** [comment]
Nach langem Suchen habe ich nun diesen Beitrag, der genau mein Problem umfasst.
Ich konnte das Problem auch soweit einschränken, dass es in in der folgenden Kombination auftritt:
MForm + MBlock + LinklistField + ein '&' Zeichen im Artikel-Namen

**Gier der Modul-Eingabe-Code:**

`$mform = new MForm();
$id = 1;
$mform->addLinklistField(1,array('label'=>'Unter-Menü'));
echo MBlock::show($id, $mform->show(), array('min'=>1,'max'=>5));`

**Test-Ergebnis:**

- LinklistField + ein '&' Zeichen -> funktioniert
- MForm + LinklistField + ein '&' Zeichen -> funktioniert
- MBlock + MForm + LinklistField + ein '&' Zeichen -> hier fehlt nach dem Speichern der Artikel-Name, das Value bzw. die ID ist weiterhin da.

Eventuell bin ich hier falsch, da es nur in Kombination mit MBlock auftritt.
Dann bitte kurz Feedback und wieder schließen.
