### ISSUE TITLE
REX_VALUE -> Array

### ISSUE THREAD

**Issue by olien** [joachimdoerr/mform#56]
[X][**0**] und [X][**11**] 

seinen nicht zu funktionieren..

**Comment by joachimdoerr** [comment]
Ja das problem ist die 0, wenn du bei 1 anfängst ist alles gut

**Comment by joachimdoerr** [comment]
wenn du 1.0 nutzen willst solltest du das in Anführungszeichen setzen, denn php frisst die .0 in float werten. also "1.0" wird gehen.

**Comment by joachimdoerr** [comment]
Close weil geklärt. Muss noch in die Doku einfließen.
