### ISSUE TITLE
$mform->addTextField + Anführungszeichen

### ISSUE THREAD

**Issue by alexplusde** [joachimdoerr/mform#57]
Hi,

wenn man das Eingabefeld, das $mform->addTextField() liefert, mit einem Anführungszeichen befüllt, wird der Inhalt danach abgeschnitten. Sollte stattdessen escaped werden, oder?

**Comment by alexplusde** [comment]
Das Problem besteht immer noch - wer ein Anführungszeichen in einem mform-Textfeld verwendet, dem wird der Text abgeschnitten. :/

**Comment by joachimdoerr** [comment]
Ich kann das problem leider nicht nachstellen habe es mit allen möglichen Anführungszeichen versucht " ` ´ '  in Textfeldern normale Input und Textareas. Kannst du mal en "demo-Text" bei dem das passiert und den entsprechenden Modul-Input veröffentlichen.

**Comment by alexplusde** [comment]
Klar, immer doch.

´´´
<?php

$mform = new mform();

$mform->addTextField(2,array('label'=>'Überschrift'));

$mform->addTextAreaField(1,array('label'=>'Textarea','class'=>"tinyMCEEditor-table"));

$mform->addMedialistField(5,array('types'=>'jpg','preview'=>1,'category'=>2,'label'=>'Bildergalerie'));

// $mForm->addSelectField(6,array(0=>'Dateinamen aufsteigend',1=>'Dateinamnen absteigend',2=>'wie oben'),array('label'=>'Sortieren nach'));



echo $mform->show_mform();

?>
```

Ich schick dir kurz ne Mail raus mit Zugangsdaten, das ist vielleicht einfacher für dich.

**Comment by joachimdoerr** [comment]
Danke jetzt sehe ich das Problem. Durch die Anführungszeichen entsteht ein Codeoutput in dieser Form

```
<input id="rv02" type="text" name="VALUE[2]" value="TEST  " test"="" asdf"="">
```

**Comment by alexplusde** [comment]
Stimmt. Das müsste das Addon doch sicher htmlspecialchars() vor der Ausgabe abfangen, oder? 
Wenn ich mir sicher wäre, wo, dann würde ich den passenden PR machen.

**Comment by joachimdoerr** [comment]
Sollte jetzt gefixt sein, bitte testen - sollte es noch Probleme geben kannst ja nochmal aufmachen. Danke für den Bugreport.

**Comment by alexplusde** [comment]
Getestet und für gut befunden.
