### ISSUE TITLE
mForm + Website Manager

### ISSUE THREAD

**Issue by alsahh** [joachimdoerr/mform#58]
Damit mForm mit dem Addon Website Manager funktionieren kann muss https://github.com/joachimdoerr/mform/blob/redaxo4/lib/classes/class.get_mform_array.php#L617 durch ```$strTable = $REX['TABLE_PREFIX'].'article_slice';``` ausgetauscht werden.

**Comment by joachimdoerr** [comment]
Super besten Dank für den Hinweis. Wird beim nächsten commit in v3.0 drin sein

**Comment by joachimdoerr** [comment]
Wurde mit dem Commit gefixt https://github.com/joachimdoerr/mform/commit/92f03c7be97a7553fb0e01ad10de2b799a121514
