### ISSUE TITLE
show_mform() zu show() ändern - in den Upgrade-Hinweisen dokumentieren

### ISSUE THREAD

**Issue by alexplusde** [joachimdoerr/mform#64]
Hatte gerade 3.0-rc1 über den Installer aktualisiert, danach gingen alle Module nicht mehr. Für andere wäre es sicher hilfreich, wenn die Änderung gleich in den Upgrade-Hinweisen dokumentiert ist.

**Comment by joachimdoerr** [comment]
Hi Alex, ja ich werd die show_form Methode nochmals einbauen. als deprecated function. Danke für den Hinweis!

**Comment by joachimdoerr** [comment]
show_mform ist nun sowohl in der 3.0.0 als auch in der 4.0.0 als deprecated drin.

https://github.com/joachimdoerr/mform/blob/master/lib/classes/MForm.php#L89-L96
https://github.com/joachimdoerr/mform/blob/redaxo4/lib/classes/MForm.php#L89-L96

**Comment by alexplusde** [comment]
:)
