### ISSUE TITLE
mform mit redactor

### ISSUE THREAD

**Issue by jfax** [joachimdoerr/mform#67]
Ich nutze Redaxo 5 mit mform und redactor. Damit redactor richtig funktioniert _(konkret: ohne das folgende können interne Links nicht gesetzt werden)_, muss dem Textarea-Feld eine ID mitgegeben werden, die mit "redactor_" beginnt. Das ist leider nicht möglich, da die ParseMForm.php in Zeile 268 hart eine ID beginnend mit rv setzt. 
`<mform:element><textarea id="rv{$varId['id']}" name="REX_IN...`
Momentan behelfe ich mit, indem ich genau diese Stelle ändere, beim nächsten Update wird dies natürlich weg sein. Könnte man an dieser Stelle einen Möglichkeit einbauen, eine ID zu setzen, da hierbei die ID nicht funktioniert? 
`$objForm->addTextAreaField(2,array('class' => 'meineklasse', 'data-id' => 'meindataattribut', 'id' => 'redactor_1'));`

**Comment by joachimdoerr** [comment]
rv als Prefix für die id wurde für den label for integriert - generell darf id auch nicht ausschließlich numerisch sein und da aus der rex_var id die id gestellt wird wurde da ein prefix integriert. Das ist in jedem fall gut den Prefix optional änderbar zu gestalten. Ich werd das im nächsten Update berücksichtigen.

**Comment by joachimdoerr** [comment]
https://github.com/joachimdoerr/mform/commit/427b472687accc264aad45365879bb890e893262
